### ISSUE TITLE
Postgres patches break the transmart-data upload

### ISSUE THREAD

**Issue by kforner** [mirasrael/tMDataLoader#2]
Hello,
I noticed that after applying the DB patches for Postgres (migrations.sql etc...) the 
https://github.com/transmart/transmart-data upload process of sample datasets do not work anymore.
I mean the 

```
make -C samples/{oracle,postgres} load_clinical_GSE8581
make -C samples/{oracle,postgres} load_ref_annotation_GSE8581
make -C samples/{oracle,postgres} load_expression_GSE8581
```

stuff

Please ask if you need more information, I will relaunch the whole process.

**Comment by mirasrael** [comment]
Thanks @kforner. We will investigate incompatibility issues and let you know if we will need any help.

**Comment by baroleg** [comment]
@kforner Could you please attach log of kettle job on your instance? We checked on own instance and we couldn't reproduced the issue. Please, clarify what version of  tMDataLoader do you use?

**Comment by kforner** [comment]
sure. Doing so I just realized I did a mistake, I forgot to checkout the post_GPL1.1.0_fixes.
Anyway:

using the master of eugene-rakhmatulin/tMDataLoader (commit 4e8d509f46548110d899e7e23eeec6bcd64a9267)
I patched:

```
psql -h db -d transmart -f migrations.sql &&     psql -h db  -d transmart -f permissions.sql &&     psql -h db  -d transmart -f procedures.sql
```

then 
using commit 2f5783508f197d066e4cb0cdd4a041d265a88e1b of https://github.com/transmart/transmart-data.git:

```
make -C samples/postgres load_clinical_GSE8581
```

then:

```


------------> Linenr 1------------------------------
i2b2_load_clinical_data params

study_id = GSE8581
top_node = \Public Studies\GSE8581\
secure_study = N
highlight_study = N
job_id =  000000000000000000018288.00

====================
INFO  29-05 13:46:49,785 - Uppercase STUDY_ID - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
INFO  29-05 13:46:49,786 - If field value is null - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
INFO  29-05 13:46:49,788 - Write to log - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
ERROR 29-05 13:46:49,791 - run i2b2_load_clinical_data - Because of an error, this step can't continue: 
Unable to call procedure
ERROR: permission denied for function i2b2_load_clinical_data

INFO  29-05 13:46:49,792 - run i2b2_load_clinical_data - Finished processing (I=0, O=0, R=1, W=0, U=0, E=1)
ERROR 29-05 13:46:49,792 - run_i2b2_load_clinical_data - Errors detected!
INFO  29-05 13:46:49,792 - run_i2b2_load_clinical_data - run_i2b2_load_clinical_data
ERROR 29-05 13:46:49,792 - run_i2b2_load_clinical_data - Errors detected!
INFO  29-05 13:46:49,792 - run_i2b2_load_clinical_data - run_i2b2_load_clinical_data
```

I'll try again with the new repository

**Comment by kforner** [comment]
Just checked with latest commit from new repository 8c48a477914b92dcd3473052e20fb15cb89d6629 (https://github.com/ThomsonReuters-LSPS/tMDataLoader.git)
same results:

```
------------> Linenr 1------------------------------
i2b2_load_clinical_data params

study_id = GSE8581
top_node = \Public Studies\GSE8581\
secure_study = N
highlight_study = N
job_id =  000000000000000000018288.00

====================
INFO  29-05 14:06:51,244 - Uppercase STUDY_ID - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
INFO  29-05 14:06:51,245 - If field value is null - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
INFO  29-05 14:06:51,247 - Write to log - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
ERROR 29-05 14:06:51,247 - run i2b2_load_clinical_data - Because of an error, this step can't continue: 
Unable to call procedure
ERROR: permission denied for function i2b2_load_clinical_data

INFO  29-05 14:06:51,247 - run i2b2_load_clinical_data - Finished processing (I=0, O=0, R=1, W=0, U=0, E=1)
INFO  29-05 14:06:51,248 - run_i2b2_load_clinical_data - run_i2b2_load_clinical_data
ERROR 29-05 14:06:51,248 - run_i2b2_load_clinical_data - Errors detected!
INFO  29-05 14:06:51,248 - run_i2b2_load_clinical_data - run_i2b2_load_clinical_data
ERROR 29-05 14:06:51,248 - run_i2b2_load_clinical_data - Errors detected!
```

**Comment by mirasrael** [comment]
@kforner, from error log I can see it fails with permission denied error. It may be result of either using wrong user or corrupted permissions, but tMDataLoader doesn't change permissions for this procedure (even more, it uses different schema - tm_dataloader - for own procedures for PostgreSQL version).
Only version I have that it may be result of applying fixes from post_GPL1.1.0_fixes which shouldn't be applied on version 1.2 database.
I recommend you check user and if it is ok, then try to create fresh database and apply only sql from tMDataLoader.

**Comment by kforner** [comment]
If I do not apply the patches it runs fine with the exact same user.
 And note that I also tried with the latest patches from master.
PGUSER=postgres
PGDATABASE=transmart

**Comment by mirasrael** [comment]
Sorry, I didn't understand. Did you apply for your database?

``` bash
cd transmartApp-DB/postgresql_wGEO
psql -d transmart -f post_1.1.0_update.sql
```

I suspect it may be a problem if you applied this patch. 
I just can't find changes in SQL patches from tMDataLoader which may lead to this problem with permissions.

**Comment by kforner** [comment]
No I did not. This did not work, and I was told it was deprecated.

**Comment by mirasrael** [comment]
Yes, but may be it was partially applied. So you ran these scripts before on this database?

**Comment by mirasrael** [comment]
Can you please attach code of tm_cz.i2b2_load_clinical_data for your database version?

**Comment by kforner** [comment]
no. Each time I do a test I start from scratch.

**Comment by kforner** [comment]
@mirasrael: How do I do this ?

**Comment by mirasrael** [comment]
You can connect to database using pgAdmin, then find procedure in data objects tree, then select in popup menu Scripts -> Create script. It will show procedure creation script. Just save it to file and attach to issue.

**Comment by kforner** [comment]
ok. I got the source of the tm_cz.i2b2_load_clinical_data before and after applying the tMdataloader patches. Here's the diff:

```
diff i2b2_load_clinical_data.before.txt i2b2_load_clinical_data.after.txt
1290,1291c1290,1291
<   OWNER TO tm_cz;
< GRANT EXECUTE ON FUNCTION tm_cz.i2b2_load_clinical_data(character varying, character varying, character varying, character varying, numeric) TO tm_cz;
---
>   OWNER TO postgres;
> GRANT EXECUTE ON FUNCTION tm_cz.i2b2_load_clinical_data(character varying, character varying, character varying, character varying, numeric) TO postgres;

```

**Comment by mirasrael** [comment]
@kforner, we found issue and fixed it in 527fedb9d9daf896d72f1849b50466ea45983adc. Your investigation was very helpful!

**Comment by kforner** [comment]
good, I'll test it ASAP

**Comment by kforner** [comment]
Ok, I confirm that it's working now. Thanks.
